global:
  evaluation_interval: 10s

scrape_configs:
  - job_name: opensearch
    scrape_interval: 10s
    metrics_path: "/_prometheus/metrics"
    static_configs:
    - targets:
      - opensearch-node1:9200
      - opensearch-node2:9200

  - job_name: kafka-exporter
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: /metrics
    scheme: http
    static_configs:
    - targets:
      - kafka-exporter:9308

  - job_name: jmx-exporter
    honor_timestamps: true
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: /metrics
    scheme: http
    static_configs:
    - targets:
      - kafka:9404