global:
  evaluation_interval: 10s

scrape_configs:
  - job_name: opensearch
    scrape_interval: 15s
    metrics_path: "/_prometheus/metrics"
    static_configs:
    - targets:
      - opensearch-node1:9200
      - opensearch-node2:9200

  - job_name: kafka-exporter
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: /metrics
    scheme: http
    static_configs:
    - targets:
      - kafka-exporter:9308

  - job_name: jmx-exporter
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: /metrics
    scheme: http
    static_configs:
    - targets:
      - kafka:9404
  
  - job_name: logstash-json-exporter
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: /probe
    static_configs:
      - targets:
          - http://logstash:9675/_node/stats/
    relabel_configs:
    - source_labels: [__address__]
      target_label: __param_target
    - source_labels: [__param_target]
      target_label: instance
    - target_label: __address__
      replacement: json_exporter:7979