{
 "title": "Logstash Metrics",
 "description": "System, JVM, and Pipeline stats",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "System",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Uptime ",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "logstash_jvm_uptime_in_millis{}",
     "legendFormat": "UP"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(logstash_events_in{}[$__range]))",
     "legendFormat": "IN"
    },
    {
     "expr": "sum(increase(logstash_events_out{}[$__range]))",
     "legendFormat": "OUT"
    }
   ]
  },
  {
   "title": " Pipeline workers",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 7, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "logstash_pipeline_workers{}" }
   ]
  },
  {
   "title": "Reloads (failures)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 10, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "logstash_reloads_failures{}" }
   ]
  },
  {
   "title": "Reloads (successes)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 13, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "logstash_reloads_successes{}" }
   ]
  },
  {
   "title": " Pipeline Batch Delay",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "logstash_pipeline_batch_delay{}"
    }
   ]
  },
  {
   "title": " Pipeline Batch Size",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 19, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "logstash_pipeline_batch_size{}" }
   ]
  },
  {
   "title": "Process (total vmem)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "logstash_process_mem_total_virtual_in_bytes{}",
     "legendFormat": "{{instance_pqdn}}-logstash_total_vmem"
    }
   ]
  },
  {
   "title": "Process (file descriptors)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 11, "y": 6 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "logstash_process_max_file_descriptors{}",
     "legendFormat": " {{instance_pqdn}}-max_fds"
    },
    {
     "expr": "logstash_process_open_file_descriptors{}",
     "legendFormat": "{{instance_pqdn}}-open_fds"
    },
    {
     "expr": "logstash_process_peak_open_file_descriptors{}",
     "legendFormat": "{{instance_pqdn}}-peak_open_fds"
    }
   ]
  },
  {
   "title": "Events In",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "targets": [
    { "expr": "logstash_events_in{}" }
   ]
  },
  {
   "title": "Events Out",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "targets": [
    { "expr": "logstash_events_out{}" }
   ]
  },
  {
   "title": "JVM",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Old pool usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "logstash_pools_old_committed_in_bytes{}",
     "legendFormat": "{{instance_pqdn}}-old_pool_committed"
    },
    {
     "expr": "logstash_pools_old_max_in_bytes{}",
     "legendFormat": "{{instance_pqdn}}-old_pool_max"
    },
    {
     "expr": "logstash_pools_old_peak_max_in_bytes{}",
     "legendFormat": "{{instance_pqdn}}-old_pool_peak_max"
    },
    {
     "expr": "logstash_pools_old_peak_used_in_bytes{}",
     "legendFormat": "{{instance_pqdn}}-old_pool_peak_used"
    },
    {
     "expr": "logstash_pools_old_used_in_bytes{}",
     "legendFormat": "{{instance_pqdn}}-old_used"
    }
   ]
  },
  {
   "title": "Young pool usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 23 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "logstash_pools_young_committed_in_bytes{}",
     "legendFormat": "{{instance_pqdn}}-young_pool_commited"
    },
    {
     "expr": "logstash_pools_young_max_in_bytes{}",
     "legendFormat": "{{instance_pqdn}}-young_pool_max"
    },
    {
     "expr": "logstash_pools_young_peak_max_in_bytes{}",
     "legendFormat": "{{instance_pqdn}}-young_pool_peak_max"
    },
    {
     "expr": "logstash_pools_young_peak_used_in_bytes{}",
     "legendFormat": "{{instance_pqdn}}-young_pool_peak_used"
    },
    {
     "expr": "logstash_pools_young_used_in_bytes{}",
     "legendFormat": "{{instance_pqdn}}-young_pool_used"
    }
   ]
  },
  {
   "title": "Survivor pool usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 23 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "logstash_pools_survivor_committed_in_bytes{}",
     "legendFormat": "{{instance_pqdn}}-survivor_pool_commited"
    },
    {
     "expr": "logstash_pools_survivor_max_in_bytes{}",
     "legendFormat": "{{instance_pqdn}}-survivor_pool_max"
    },
    {
     "expr": "logstash_pools_survivor_peak_max_in_bytes{}",
     "legendFormat": "{{instance_pqdn}}-survivor_pool_peak_max"
    },
    {
     "expr": "logstash_pools_survivor_peak_used_in_bytes{}",
     "legendFormat": "{{instance_pqdn}}-survivor_pool_peak_used"
    },
    {
     "expr": "logstash_pools_survivor_used_in_bytes{}",
     "legendFormat": "{{instance_pqdn}}-survivor_pool_used"
    }
   ]
  },
  {
   "title": "Old Colletions Count",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ceil(increase(logstash_gc_old_collection_count{}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average time spent for GC (yound & old gens in ms)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 4, "y": 29 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "logstash_gc_old_collection_time{}/logstash_gc_old_collection_count{}",
     "legendFormat": "{{instance_pqdn}}-gc-old"
    },
    {
     "expr": "logstash_gc_young_collection_time{}/llogstash_gc_young_collection_count{}",
     "legendFormat": "{{instance_pqdn}}-gc-young"
    }
   ]
  },
  {
   "title": "Threads count",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "logstash_jvm_threads_count{}",
     "legendFormat": "{{instance_pqdn}}-threads_count"
    },
    {
     "expr": "logstash_jvm_threads_peak_count{}",
     "legendFormat": "{{instance_pqdn}}-threads_peak"
    }
   ]
  },
  {
   "title": "Young Colletions Count",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ceil(increase(logstash_gc_young_collection_count{}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "JVM Heap % used",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "logstash_jvm_mem_heap_used_percent{}",
     "legendFormat": "{{instance_pqdn}}-jvm-usage"
    }
   ]
  },
  {
   "title": "JVM Heap usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 35 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "logstash_jvm_mem_heap_max_in_bytes{}",
     "legendFormat": "{{instance_pqdn}}-jvm-max"
    },
    {
     "expr": "logstash_jvm_mem_heap_used_in_bytes{}",
     "legendFormat": "{{instance_pqdn}}-jvm-used"
    }
   ]
  },
  {
   "title": "Pipeline",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Pipeline Event Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "irate(logstash_events_duration_in_millis{}[$__range])",
     "legendFormat": "{{pipeline}}"
    }
   ]
  },
  {
   "title": "Pipeline Event In",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "irate(logstash_events_in{}[$__range])",
     "legendFormat": "{{pipeline}}"
    }
   ]
  },
  {
   "title": "Pipeline Queue Push Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "irate(logstash_queue_push_duration_in_millis{}[$__range])",
     "legendFormat": "{{pipeline}}"
    }
   ]
  },
  {
   "title": "Pipeline Event Out",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "irate(logstash_events_out{}[$__range])",
     "legendFormat": "{{pipeline}}"
    }
   ]
  },
  {
   "title": "Pipeline Event Filtered",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "irate(logstash_events_filtered{}[$__range])",
     "legendFormat": "{{pipeline}}"
    }
   ]
  },
  {
   "title": "Processed events (I/O)/ sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "logstash_events_out{}/(logstash_events_duration_in_millis{}/1000)",
     "legendFormat": "{{instance_pqdn}} - processed events/sec"
    },
    {
     "expr": "logstash_events_in{}/(logstash_queue_push_duration_in_millis{}/1000)",
     "legendFormat": "{{pipeline}} - pushed events/sec"
    }
   ]
  },
  {
   "title": "Pipeline input events / sec over the last hour",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(logstash_events_in{}[$__range])",
     "legendFormat": "{{pipeline}}"
    },
    {
     "expr": "sum by (job) (irate(logstash_events_in{}[$__range]))",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Events processing times",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "logstash_queue_push_duration_in_millis{}/logstash_events_in{}",
     "legendFormat": "{{instance_pqdn}} - avg waiting time"
    },
    {
     "expr": "logstash_events_duration_in_millis{}/logstash_events_out{}",
     "legendFormat": "{{instance_pqdn}} - avg process time"
    }
   ]
  },
  { "title": "Queue", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 74 } },
  {
   "title": "Pipeline Queue Count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "logstash_queue_events_count{}" }
   ]
  },
  {
   "title": "Queue Backpressure (current)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "logstash_flow_queue_backpressure_current{}"
    }
   ]
  }
 ]
}